# Generated by Django 2.2.3 on 2020-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='Conf_pass',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='create',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='create',
            name='Password',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='create',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
