# Generated by Django 2.2.3 on 2020-08-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200724_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create',
        ),
    ]
